name: "Azure Machine Learning Register Model Action"
description: "Register a model in your Azure Machine Learning Workspace with this GitHub Action"
author: "azure/gh-aml"
inputs:
  azureCredentials:
    description: "Paste output of `az ad sp create-for-rbac --name <your-sp-name> --role contributor --scopes /subscriptions/<your-subscriptionId>/resourceGroups/<your-rg> --sdk-auth` as value of secret variable: AZURE_CREDENTIALS"
    required: true
  runId:
    description: "ID of the run or pipeline run for which a model is to be registered"
    required: true
  experimentName:
    description: "Experiment to which the run belongs to"
    required: true
  parametersFile:
    description: "JSON file including the parameters for registering the model."
    required: true
    default: "registermodel.json"
outputs:
  modelName:
    description: "Name of the registered model"
  modelVersion:
    description: "Version of the registered model"
  modelId:
    description: "ID of the registered model"
branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
