name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      # create or connect to a new Workspace
      - name: Connect or Create Workspace
        id: ws_connect
        uses: azure/aml-workspace@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_workspace.json"

      # register a given model with AML
      - name: Register a Model from compute
        id: ws_registerModel
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id: "aml-run-intTest_1589096763_b5ed2189"
          experiment_name: "aml-run-intTest"
          parameters_file: "test/test_registermodel.json"

      # register a given model from local system with AML; do not provide run id if model is from local repo
      - name: Register a Model from compute
        id: ws_registerModel_local
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          experiment_name: "aml-run-intTest"
          parameters_file: "test/test_registermodel_fromlocal.json"